### ISSUE TITLE
请问mongodb起来了最后运行run.sh的时候web5000端口服务起不来是什么原因

### ISSUE THREAD

**Issue by Mr89898** [jeffzh3ng/InsectsAwake#5]
nohup: ignoring input
Traceback (most recent call last):
File "./InsectsAwake.py", line 12, in 
from InsectsAwake.views.modules.scanner.pocsuite_scanner import scanner_loop_execute
File "/tmp/InsectsAwake/InsectsAwake/views/modules/scanner/pocsuite_scanner.py", line 21, in 
scanner_thread = int(connectiondb(config_db).find_one()['scanner_thread'])
File "/tmp/InsectsAwake/InsectsAwake/views/lib/mongo_db.py", line 25, in connectiondb
db.authenticate(db_username, db_password)
File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 1167, in authenticate
connect=True)
File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 588, in _cache_credentials
sock_info.authenticate(credentials)
File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 620, in authenticate
auth.authenticate(credentials, self)
File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 486, in authenticate
auth_func(credentials, sock_info)
File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 466, in _authenticate_default
return _authenticate_scram_sha1(credentials, sock_info)
File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
res = sock_info.command(source, cmd)
File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 517, in command
collation=collation)
File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 125, in command
parse_write_concern_error=parse_write_concern_error)
File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 145, in _check_command_response
raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.

**Comment by jeffzh3ng** [comment]
你可以把项目目录里面的log文件贴出来，给我看一下嘛

**Comment by starrkdevil** [comment]
我遇见同样的情况，你查看一下mongdb服务是不是挂掉了。先将InsectAwake停止，重启mongdb服务，最后在执行 ./run.sh start 应该就可以了。

**Comment by Mr89898** [comment]
没挂就是web服务起不来

**Comment by Mr89898** [comment]
nohup: ignoring input
Traceback (most recent call last):
  File "./InsectsAwake.py", line 12, in <module>
    from InsectsAwake.views.modules.scanner.pocsuite_scanner import scanner_loop_execute
  File "/tmp/InsectsAwake/InsectsAwake/views/modules/scanner/pocsuite_scanner.py", line 21, in <module>
    scanner_thread = int(connectiondb(config_db).find_one()['scanner_thread'])
  File "/tmp/InsectsAwake/InsectsAwake/views/lib/mongo_db.py", line 25, in connectiondb
    db.authenticate(db_username, db_password)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 1167, in authenticate
    connect=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 588, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 620, in authenticate
    auth.authenticate(credentials, self)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 486, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 466, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 517, in command
    collation=collation)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.

**Comment by jeffzh3ng** [comment]
数据库认证错误，你创建用户了吗？可以使用创建的用户正常连接数据库吗？

**Comment by Mr89898** [comment]
我有创建了数据库，

**Comment by crhua** [comment]
crhua@ubuntu:~/Desktop/InsectsAwake$ sudo ./run.sh start
Starting  Now......
Starting  Finished
crhua@ubuntu:~/Desktop/InsectsAwake$ nohup: ignoring input and redirecting stderr to stdout
nohup: redirecting stderr to stdout


这个怎么解决

**Comment by jeffzh3ng** [comment]
这个敲一下回车就好，程序会在后台运行，参考：https://blog.csdn.net/educast/article/details/28273301
